### PR TITLE
add script to diagnose the merged output heppy file validity

### PR DESCRIPTION
**Pull request by davidjamin**

### CODE REVIEW

**Comment by clementhelsens** [comment]
Hi @cbernet, 

David added this script because we found a large fraction of corrupted files after the heppy_hadd step. So this flags when it produces a corrupted merged files so that we can proceed again with the merging.
Have you ever experienced such problems?
@davidjamin , could you please post the error that we observe when the file is corrupted?

Cheers,
Clement

**Comment by davidjamin** [comment]
Hi @cbernet ,
as said by @clementhelsens I put here few lines of the error happening on a problematic event : 
...
R__unzip: error -5 in inflate (zlib)
Error in <TBasket::ReadBasketBuffers>: fNbytes = 30287, fKeylen = 94, fObjlen = 31904, noutot = 0, nout=0, nin=30193, nbuf=31904
 file probably overwritten: stopping reporting error messages
Error in <TBranch::GetBasket>: File: FCChhAnalyses/output/BDT_v02_mvaQCD/Chunk_backup/Zprime_tt/pp_Zprime_20TeV_ttbar.bad/heppy.FCChhAnalyses.Zprime_tt.TreeProducer.TreeProducer_1/tree.root at byte:90294230, branch:Jet1_trk02_Corr_MetCorr_e, entry:111658, badread=1, nerrors=10, basketnumber=13
R__unzip: error -5 in inflate (zlib)
Error in <TBasket::ReadBasketBuffers>: fNbytes = 30287, fKeylen = 94, fObjlen = 31904, noutot = 0, nout=0, nin=30193, nbuf=31904
...

it can happen that such error crash our code. The file used for the above error is here : 

/afs/cern.ch/user/d/djamin/fcc_work/heppy/FCChhAnalyses/output/BDT_v02_mvaQCD/Chunk_backup/Zprime_tt/pp_Zprime_20TeV_ttbar.bad/heppy.FCChhAnalyses.Zprime_tt.TreeProducer.TreeProducer_1/tree.root

Cheers,
David

**Comment by cbernet** [comment]
Hi David, 

heppy_hadd is just using ROOT’s hadd. 
Can you try hadd directly on your root files? 

Cheers, 

Colin

**Comment by davidjamin** [comment]
Hi Colin,

yes I did and the output is OK but I am not sure to reproduce or fix the 
issue with such a test.

When we use our script to merge the files it can happen that some of the 
produced merged files have corrupted events but it doesn't happen every 
time (and later on when we run on these files, the codes are crashing). 
The goal of my script is to find the corrupted merged files. Then I 
re-run our merging script to make these specific files again and the new 
files are OK after a second try with the exact same merging script (it 
has never been needed to run a 3rd time).

I am not sure that using hadd directly is preventing the issue : I do 
once hadd command and the output is fine but I do not learn anything.

In a second hand, I am not sure how to spot what is not working in our 
merging script.
Cheers,
David.

**Comment by cbernet** [comment]
Hi David, 

Can you simply keep the script in some other place? like the hh analysis package? 
It is the first time I hear about this problem, and it is definitely related to hadd (and/or your input files).

Cheers, 

Colin

**Comment by davidjamin** [comment]
OK I move it in hh analysis package

**Pull request closed without merging**
