### PR TITLE
Update FCC context

### PR DESCRIPTION
**Pull request by vvolkl**
The FCC software no longer uses the environment variables it used to.

### CODE REVIEW

**Comment by vvolkl** [comment]
No problem! I was packaging heppy for use in a docker image and had a few more fixes. Would be great if you can take a look once I get around to opening the PRs.

@JavierCVilla  could you check our jenkins instance? the build looks like something is wrong

**Comment by cbernet** [comment]
Btw heppy is now available on pypi:
https://pypi.org/project/heppyfwk/

Maybe we want to pick it up from there now?

Cheers,

Colin



On 13 Feb 2019, at 13:35, vvolkl <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem! I was packaging heppy for use in a docker image and had a few more fixes. Would be great if you can take a look once I get around to opening the PRs.

@JavierCVilla<https://github.com/JavierCVilla> could you check our jenkins instance? the build looks like something is wrong

**Comment by clementhelsens** [comment]
@cbernet, how do we handle FCC specific developments then?

Le 13 févr. 2019 à 13:41, Colin Bernet <notifications@github.com<mailto:notifications@github.com>> a écrit :

Btw heppy is now available on pypi:
https://pypi.org/project/heppyfwk/

Maybe we want to pick it up from there now?

Cheers,

Colin



On 13 Feb 2019, at 13:35, vvolkl <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


No problem! I was packaging heppy for use in a docker image and had a few more fixes. Would be great if you can take a look once I get around to opening the PRs.

@JavierCVilla<https://github.com/JavierCVilla> could you check our jenkins instance? the build looks like something is wrong

**Comment by cbernet** [comment]
As usual, we do Prs to HEP-FCC/heppy.
And when the responsible person decides to draft a release, (s)he uploads to pypi


On 13 Feb 2019, at 14:14, clementhelsens <notifications@github.com<mailto:notifications@github.com>> wrote:

@cbernet, how do we handle FCC specific developments then?

Le 13 févr. 2019 à 13:41, Colin Bernet <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> a écrit :

Btw heppy is now available on pypi:
https://pypi.org/project/heppyfwk/

Maybe we want to pick it up from there now?

Cheers,

Colin



On 13 Feb 2019, at 13:35, vvolkl <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


No problem! I was packaging heppy for use in a docker image and had a few more fixes. Would be great if you can take a look once I get around to opening the PRs.

@JavierCVilla<https://github.com/JavierCVilla> could you check our jenkins instance? the build looks like something is wrong

**Comment by JavierCVilla** [comment]
> @JavierCVilla could you check our jenkins instance? the build looks like something is wrong

The current CI setup was still using afs...

```
/afs/cern.ch/exp/fcc/sw/0.8pre/setup.sh
```

changing it to the current FCC externals.

**Comment by JavierCVilla** [comment]
Still [failing](https://epsft-jenkins.cern.ch/job/HEPPY-pullrequests/BUILDTYPE=Release,COMPILER=gcc49,LABEL=slc6/96/console)

**Comment by vvolkl** [comment]
@JavierCVilla thanks, this looks now like an actual problem with the PR, will take a look

@cbernet great, I think using pipy is very nice!

**Comment by JavierCVilla** [comment]
@phsft-bot build

**Comment by vvolkl** [comment]
@phsft-bot build

**Comment by vvolkl** [comment]
@phsft-bot  build

**Comment by vvolkl** [comment]
@phsft-bot  build

**Comment by vvolkl** [comment]
test this please

**Comment by vvolkl** [comment]
Superseded by #96

**Pull request closed without merging**
